/** @type {import('tailwindcss').Config} */ 
module.exports = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontSize: {
      'xs': '1rem',
      'sm': '1.2rem',
      'tiny': '1.6rem',
      'base': '1.8rem',
      'lg': '2rem',
      'xl': '2.12rem',
      '2xl': '2.25rem',
      '3xl': '2.5rem',
      '4xl': '2.75rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
    },
    colors: {},
    textColor: {
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      theme: "var(--color-text-theme)",
      "default-soft": "var(--color-text-default-soft)",
      inverse: "var(--color-text-inverse)",
      "inverse-soft": "var(--color-text-inverse-soft)",
      heart: "var(--color-bg-secondary)",
      white: "#fdfdfd",
      beige: "#f4efed",
      grey: "777",
      slate: "rgb(156 163 175)",
    },
    backgroundColor: {
      primary: {
        default: "var(--color-bg-primary)",
        light: "var(--color-bg-primary-light)",
        medium: "var(--color-bg-primary-medium)",
        dark: "var(--color-bg-primary-dark)",
        grey: "#ccc",
      },
      secondary: "var(--color-bg-secondary)",
      default: "var(--color-bg-default)",
      inverse: "var(--color-bg-inverse)",
      beige: "#f4efed",
      surface: "var(--color-surface)",
      twitter: "var(--color-social-twitter)",
      facebook: "var(--color-social-facebook)",
      reddit: "var(--color-social-reddit)",
      pinterest: "var(--color-social-pinterest)",
    },
    fontWeights: {
      light: "300",
      normal: "400",
      semibold: "500",
      bold: "600"
    },
  },
  plugins: [],
}